export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const NEW_POST = "NEW_POST";
export const SIGN_UP = "SIGN_UP";
export const CHECK_TOKEN = "CHECK_TOKEN";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const PATCH_PRODUCT = "PATCH_PRODUCT";
export const PATCH_ENTITY = "PATCH_ENTITY";
export const POST_PRODUCT = "POST_PRODUCT";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const FETCH_FAVORITE = "FETCH_FAVORITE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
